// <auto-generated />
using MailScan.SQLiteModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MailScan.Migrations
{
    [DbContext(typeof(maildbContext))]
    partial class maildbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("MailScan.SQLiteModels.BlockedAddress", b =>
                {
                    b.Property<long>("PkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pkID");

                    b.Property<string>("Emai")
                        .HasColumnType("STRING");

                    b.HasKey("PkId");

                    b.ToTable("BlockedAddresses");
                });

            modelBuilder.Entity("MailScan.SQLiteModels.BlockedDomain", b =>
                {
                    b.Property<long>("PkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pkID");

                    b.Property<string>("Domain")
                        .HasColumnType("STRING");

                    b.HasKey("PkId");

                    b.ToTable("BlockedDomains");
                });

            modelBuilder.Entity("MailScan.SQLiteModels.BodyKeyword", b =>
                {
                    b.Property<long>("PkId")
                        .HasColumnType("INT")
                        .HasColumnName("pkID");

                    b.Property<string>("KeyWord")
                        .HasColumnType("STRING");

                    b.HasKey("PkId");

                    b.ToTable("BodyKeywords");
                });

            modelBuilder.Entity("MailScan.SQLiteModels.MailDetail", b =>
                {
                    b.Property<long>("PkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pkID");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("STRING");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("DATETIME");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("STRING");

                    b.Property<string>("MailId")
                        .IsRequired()
                        .HasColumnType("STRING")
                        .HasColumnName("MailID");

                    b.Property<long>("Rank")
                        .HasColumnType("INT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("STRING");

                    b.HasKey("PkId");

                    b.ToTable("MailDetails");
                });

            modelBuilder.Entity("MailScan.SQLiteModels.SubjectKeyword", b =>
                {
                    b.Property<long>("PkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pkID");

                    b.Property<string>("KeyWord")
                        .HasColumnType("STRING");

                    b.HasKey("PkId");

                    b.ToTable("SubjectKeywords");
                });
#pragma warning restore 612, 618
        }
    }
}
